/**
 * academicConstants.js
 * Central constants for the Academics module on backend.
 */
const DEFAULT_TOTAL_DEGREE_CREDITS = 160
const WEAK_SUBJECT_GRADE_THRESHOLD = 6.5
const WEAK_SUBJECT_ATTENDANCE_THRESHOLD = 75
const EXCELLENT_GRADE_THRESHOLD = 8.5
const EXCELLENT_ATTENDANCE_THRESHOLD = 85

module.exports = {
  DEFAULT_TOTAL_DEGREE_CREDITS,
  WEAK_SUBJECT_GRADE_THRESHOLD,
  WEAK_SUBJECT_ATTENDANCE_THRESHOLD,
  EXCELLENT_GRADE_THRESHOLD,
  EXCELLENT_ATTENDANCE_THRESHOLD
}
