/**
 * Validation Layer (v2.0)
 *
 * Validates the fully-assembled pipeline contract.
 * Changes from v1:
 * - Allows credits = 0 (audit/mandatory courses like Constitution of India)
 * - Validates per-subject confidence field
 * - Validates summary object
 * - Adds result: "PASS" | "FAIL" flag per subject if not already set
 * - Removes false positives for "passed/failed" noise filter (was matching subject names)
 */
const { PASS_GRADE_THRESHOLD } = require('./utils/constants')

/**
 * Validates semester number boundaries.
 */
const validateSemester = (semesterNumber, warnings) => {
  if (semesterNumber === undefined || semesterNumber === null) {
    warnings.push({
      type: 'SEMESTER',
      severity: 'ERROR',
      subjectId: null,
      message: 'Semester number is missing.'
    })
    return
  }

  if (!Number.isInteger(semesterNumber) || semesterNumber < 1 || semesterNumber > 8) {
    warnings.push({
      type: 'SEMESTER',
      severity: 'ERROR',
      subjectId: null,
      message: 'Semester number must be an integer between 1 and 8.'
    })
  }
}

/**
 * Validates subject name — non-empty, 2–120 chars.
 */
const validateSubjectName = (sub, warnings) => {
  const name = sub.name ? String(sub.name).trim() : ''
  if (!name) {
    warnings.push({
      type: 'SUBJECT_NAME',
      severity: 'ERROR',
      subjectId: sub.id,
      message: 'Missing subject name.'
    })
    return
  }
  if (name.length < 2 || name.length > 120) {
    warnings.push({
      type: 'SUBJECT_NAME',
      severity: 'ERROR',
      subjectId: sub.id,
      message: 'Subject name must be between 2 and 120 characters.'
    })
  }
}

/**
 * Validates credits — integer 0–6 (0 allowed for audit courses).
 */
const validateCredits = (sub, warnings) => {
  const credits = sub.credits
  if (credits === undefined || credits === null) {
    warnings.push({
      type: 'CREDITS',
      severity: 'WARNING',
      subjectId: sub.id,
      message: 'Missing credit value.'
    })
    return
  }
  if (!Number.isInteger(credits) || credits < 0 || credits > 6) {
    warnings.push({
      type: 'CREDITS',
      severity: 'WARNING',
      subjectId: sub.id,
      message: 'Credits must be an integer between 0 and 6.'
    })
  }
}

/**
 * Validates grade mapping and value boundaries (0–10).
 */
const validateGrade = (sub, warnings) => {
  const rawGrade  = sub.rawGrade ? String(sub.rawGrade).trim() : ''
  const finalGrade = sub.finalGrade

  if (rawGrade && (finalGrade === undefined || finalGrade === null)) {
    warnings.push({
      type: 'GRADE',
      severity: 'WARNING',
      subjectId: sub.id,
      message: 'Unable to map grade.'
    })
    return
  }

  if (!rawGrade && (finalGrade === undefined || finalGrade === null)) {
    warnings.push({
      type: 'GRADE',
      severity: 'WARNING',
      subjectId: sub.id,
      message: 'Missing grade value.'
    })
    return
  }

  if (typeof finalGrade === 'number' && (finalGrade < 0 || finalGrade > 10)) {
    warnings.push({
      type: 'GRADE',
      severity: 'WARNING',
      subjectId: sub.id,
      message: 'Final grade must be between 0 and 10.'
    })
  }
}

/**
 * Validates per-subject confidence score exists and is numeric.
 */
const validateConfidence = (sub, warnings) => {
  if (sub.confidence === undefined || sub.confidence === null) {
    // Non-fatal: just add an info warning
    warnings.push({
      type: 'CONFIDENCE',
      severity: 'INFO',
      subjectId: sub.id,
      message: 'Per-subject confidence score is missing.'
    })
  }
}

/**
 * Validates result field ("PASS" | "FAIL").
 * If missing, derives it from finalGrade.
 */
const ensureResultFlag = (sub) => {
  if (sub.result !== 'PASS' && sub.result !== 'FAIL') {
    if (sub.finalGrade !== null && sub.finalGrade !== undefined) {
      sub.result = sub.finalGrade >= PASS_GRADE_THRESHOLD ? 'PASS' : 'FAIL'
    } else {
      sub.result = 'UNKNOWN'
    }
  }
}

/**
 * Validates duplicate flags.
 */
const validateDuplicates = (sub, warnings) => {
  if (sub.duplicate === true) {
    warnings.push({
      type: 'DUPLICATE',
      severity: 'WARNING',
      subjectId: sub.id,
      message: `Duplicate subject detected: "${sub.name}".`
    })
  }
}

/**
 * Validates the credit summary object (if present).
 */
const validateSummary = (summary, warnings) => {
  if (!summary) return  // Summary is optional — generated by creditCalculator

  const fields = ['totalCredits', 'earnedCredits', 'failedCredits']
  fields.forEach(f => {
    if (typeof summary[f] !== 'number') {
      warnings.push({
        type: 'SUMMARY',
        severity: 'INFO',
        subjectId: null,
        message: `Summary field "${f}" is missing or invalid.`
      })
    }
  })
}

/**
 * Builds validation summary counts.
 */
const buildSummary = (subjects = [], warnings = []) => {
  const totalSubjects = subjects.length
  const errors   = warnings.filter(w => w.severity === 'ERROR').length
  const warningsCount = warnings.filter(w => w.severity === 'WARNING').length

  let passed = 0
  subjects.forEach(sub => {
    const hasIssue = warnings.some(
      w => w.subjectId === sub.id && (w.severity === 'ERROR' || w.severity === 'WARNING')
    )
    if (!hasIssue) passed++
  })

  return { totalSubjects, passed, warnings: warningsCount, errors }
}

/**
 * Main Validation Layer entry point.
 *
 * @param {Object} sharedContract - Pipeline shared contract
 * @returns {Object} Audited contract
 */
const validateContract = (sharedContract) => {
  if (!sharedContract) return null

  const contract = JSON.parse(JSON.stringify(sharedContract))
  contract.warnings = []

  // 1. Semester
  validateSemester(contract.semesterNumber, contract.warnings)

  // 2. Subjects
  if (contract.subjects && Array.isArray(contract.subjects)) {
    contract.subjects.forEach(sub => {
      validateSubjectName(sub, contract.warnings)
      validateCredits(sub, contract.warnings)
      validateGrade(sub, contract.warnings)
      validateConfidence(sub, contract.warnings)
      validateDuplicates(sub, contract.warnings)
      ensureResultFlag(sub)   // Adds/fixes result field in-place
    })
  }

  // 3. Credit summary
  validateSummary(contract.summary, contract.warnings)

  // 4. Sort warnings: ERROR → WARNING → INFO
  const severityOrder = { ERROR: 1, WARNING: 2, INFO: 3 }
  contract.warnings.sort((a, b) => (severityOrder[a.severity] || 99) - (severityOrder[b.severity] || 99))

  // 5. Pipeline flags
  const hasErrors   = contract.warnings.some(w => w.severity === 'ERROR')
  const hasWarnings = contract.warnings.some(w => w.severity === 'WARNING')
  const canProceed  = !hasErrors

  if (!contract.metadata) contract.metadata = {}
  contract.metadata.hasErrors   = hasErrors
  contract.metadata.hasWarnings = hasWarnings
  contract.metadata.canProceed  = canProceed
  contract.metadata.validationSummary = buildSummary(contract.subjects, contract.warnings)

  return contract
}

module.exports = {
  validateContract,
  validateSemester,
  validateSubjectName,
  validateCredits,
  validateGrade,
  validateDuplicates,
  validateSummary,
  buildSummary
}
